version: "3.9"
services:
  server1:
    image: "mini-saas-server"
    ports:
      - "8080:8080"
    networks:
      - envoymesh
    environment:
      "server.id": "1"
      "server.port": "8080"

  server2:
    image: "mini-saas-server"
    ports:
      - "7070:7070"
    networks:
      - envoymesh
    environment:
      "server.id": "2"
      "server.port": "7070"

  client:
    image: "mini-saas-client"
    ports:
      - "8081:8081"
    networks:
      - envoymesh

  envoy:
    image: "envoyproxy/envoy:v1.19-latest"
    ports:
      - 9901:9901
      - 10000:10000
    volumes:
      # - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./envoy/bootstrap.yaml:/etc/envoy/bootstrap.yaml
    networks:
      - envoymesh
    command:
      - "--component-log-level http:debug,http2:debug,grpc:debug,matcher:debug,router:debug,filter:debug"
      - "-c /etc/envoy/bootstrap.yaml"

  envoy-xds-server:
    image: "envoy-xds-server"
    ports:
      - "18000:18000"
    networks:
      - envoymesh
    command:
      - "--nodeID=envoy-proxy"
      - "-debug"

networks:
  envoymesh: {}
