apiVersion: v1
kind: ConfigMap
metadata:
  name: tellery-envoy-config
  namespace: mosaic-beta
data:
  bootstrap.yaml: |-
    node:
      cluster: tellery-envoy-proxy
      id: tellery-envoy-proxy

    admin:
      access_log_path: /tmp/admin_access.log
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000

    dynamic_resources:
      cds_config:
        resource_api_version: V3
        api_config_source:
          api_type: GRPC
          transport_api_version: V3
          grpc_services:
            - envoy_grpc:
                cluster_name: xds_cluster
          set_node_on_first_message_only: true
      lds_config:
        resource_api_version: V3
        api_config_source:
          api_type: GRPC
          transport_api_version: V3
          grpc_services:
            - envoy_grpc:
                cluster_name: xds_cluster
          set_node_on_first_message_only: true

    static_resources:
      clusters:
        - name: xds_cluster
          connect_timeout: 1s
          type: STRICT_DNS
          load_assignment:
            cluster_name: xds_cluster
            endpoints:
              - lb_endpoints:
                  - endpoint:
                      address:
                        socket_address:
                          address: envoy-xds-server
                          port_value: 18000
          http2_protocol_options: {}

    layered_runtime:
      layers:
        - name: runtime-0
          rtds_layer:
            rtds_config:
              resource_api_version: V3
              api_config_source:
                transport_api_version: V3
                api_type: GRPC
                grpc_services:
                  envoy_grpc:
                    cluster_name: xds_cluster
            name: runtime-0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-proxy
  namespace: mosaic-beta
  labels:
    app: envoy-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy-proxy
  template:
    metadata:
      labels:
        app: envoy-proxy
    spec:
      containers:
        - name: envoy
          image: envoyproxy/envoy:v1.19-latest
          ports:
            - name: proxy
              containerPort: 9901
              protocol: TCP
            - name: admin
              containerPort: 10000
              protocol: TCP
          resources: {}
          args:
            - "-c /etc/envoy/bootstrap.yaml"
          volumeMounts:
            - name: config
              mountPath: /etc/envoy
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: tellery-envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-proxy
  namespace: mosaic-beta
  labels:
    app: envoy-proxy
spec:
  selector:
    app: envoy-proxy
  ports:
    - name: proxy
      port: 9901
      targetPort: 9901
    - name: management
      port: 10000
      targetPort: 10000